import localFont from "next/font/local";
import "./globals.css";
import { ProviderContext } from "./context/PostContext";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body>
        <ProviderContext>
           {children}
        </ProviderContext>
      </body>
     
    </html>
  );
}
